# Generated by Django 4.2.28 on 2026-02-11 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='users.department'),
        ),
        migrations.AddField(
            model_name='expense',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
