# Generated by Django 4.2.28 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
