# Generated by Django 4.2.28 on 2026-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_paid_at_expense_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FINANCE_REVIEW', 'Finance Review'), ('COO_REVIEW', 'COO Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseapprovalhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'created_at'], name='expenses_ex_status_a69693_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['department', 'status'], name='expenses_ex_departm_71a081_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['initiator', 'status'], name='expenses_ex_initiat_3f90d1_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseapprovalhistory',
            index=models.Index(fields=['expense', 'timestamp'], name='expenses_ex_expense_9622da_idx'),
        ),
    ]
