# Generated by Django 4.2.28 on 2026-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('submit', 'Submit Expense'), ('approve', 'Approve Expense'), ('reject', 'Reject Expense'), ('payment', 'Payment Processed'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=20)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
